AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^axf/",include('app.urls',namespace="axf")),
]

AXF/app/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r"^home$",home,name="home"),
    url(r"^market$",market,name="market"),
    url(r"^market_with_params/(\d+)/(\d+)/(\d+)", market_with_params, name="market_with_params"),
    url(r"^cart$",cart,name="cart"),
    url(r"^mine$",mine,name="mine"),
    url(r"^register$",RegisterAPI.as_view(),name="register"),
    url(r"^login$",LoginAPI.as_view(),name="login"),
    url(r"^confirm/(.*)",confirm_api),
    url(r"^logout$",logout_api,name="logout"),
    url(r"^cartapi$",cart_api,name="cart_api"),
    url(r"^cart_status$",cart_status_api),
    url(r"^select_all_api$",select_all_api),
    url(r"^cartitem_api$",cartitem_api),
    url(r"^order$",order_api,name="order")
]

AXF/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/swiper.css'%}">
    <link rel="stylesheet" href="{%static 'css/reset.css'%}">
{#    每个页面要定义的css#}
    {% block css %}
    
    {% endblock %}
</head>
<body>
{#    头部#}
    {% block header %}
    
    {% endblock %}
{#    中间部分#}
    {% block content %}

    {% endblock %}
{#    腿部#}
    {% block footer %}
    
    {% endblock %}
</body>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

{#    每个页面独有的js#}
    {% block js %}

    {% endblock %}

</html>

AXF/templates/base/base_main.html
{% extends 'base/base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url "axf:home" %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}

AXF/templates/base/base_user.html
{% extends 'base/base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}