day07/app7/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r"^person/(\d+)",persons_api,name="person"),
    url(r"^img",get_confirm_img,name="img"),
    url(r"^my_login$",my_login),
    url(r"^confirm$",confirm_api)
]

day07/day07/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^app7/",include("app7.urls",namespace="app7"))
]

day07/app7/models.py
from django.db import models

# Create your models here.

class Home(models.Model):
    name = models.CharField(
        max_length=30,
        verbose_name="家庭名字"
    )


class Person(models.Model):
    name = models.CharField(
        verbose_name="名字",
        max_length=30
    )
    age = models.IntegerField(
        verbose_name="年纪"
    )
    home = models.ForeignKey(
        Home,
        null=True
    )
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="人类"

day07/app7/views.py
import os
import random

from PIL import Image,ImageDraw,ImageFont
from django.conf import settings
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from .models import Person
from .util import get_random_color
import io

# Create your views here.
PAGE_PEER_NUM = 10

def persons_api(req,current_page):
    # 拿到全部数据
    persons = Person.objects.all()
    # 实例化分页对象
    paginator = Paginator(
        persons,
        PAGE_PEER_NUM
    )
    # 需要知道用户点了第几页的数字按钮，所以需要前端传递的页码参数
    datas = []
    try:
        # 通过参数拿到对应得page对象
        page = paginator.page(current_page)
        # 获得页码里得数据
        datas = page.object_list
    except:
        pass
    data = {
        "persons": datas,#page.object_list
        "page_range": paginator.page_range,
        "page":page,
        "last_page":paginator.num_pages
    }
    return render(req,"paginator.html",data)

def get_confirm_img(req):
    # 有一个颜色
    bg = get_random_color()
    # 设置画布大小
    img_size = (150,50)  # 第一个参数是宽度  第二个是高度
    # 实例化一个画布
    image = Image.new("RGB",img_size,bg)
    # 实例化 一个画笔
    draw = ImageDraw.Draw(image)
    # 实例化一个字体
    font_path = os.path.join(settings.BASE_DIR,"static/fonts/ADOBEARABIC-BOLDITALIC.OTF")
    font_size = 30
    my_font = ImageFont.truetype(font_path, font_size)
    # 验证字母得数据源
    source = "zxcvbnmasdfghjklqwertyuiopZXCVBNMASDFGHJKLQWERTYUIOP1234567890"
    # 循环次数
    loop = 4
    confirm_code = ""
    for i in range(loop):
        # 生成一个随机数字
        tmp = random.randrange(len(source))
        # 获得随机数字对应下标得字母
        tmp_str = source[tmp]
        # 记录生成的每个字符
        confirm_code += tmp_str
        # 生成随机颜色
        font_color = get_random_color()
        # 将字母画到画布
        draw.text((20+30*i, 10), tmp_str, font_color, font=my_font)
    # draw.text((20,10),"y",font_color,font=my_font)

    # 保存
    buf = io.BytesIO()
    # 将图片保存到路由里
    image.save(buf,"png")

    # 设置session  将生成的四位的验证码保存到session
    req.session["c_code"] = confirm_code
    return HttpResponse(buf.getvalue(),content_type="image/png")

def my_login(req):
    return render(req,"login.html")

def confirm_api(req):
    # 先拿到用户传递过来得参数
    user_code = req.POST.get("code")
    # 从session里拿生成得验证码字符
    bg_code = req.session.get("c_code")
    # 不区分大小写验证  lower
    # 根据不同得比对结果给予不同的反馈
    if user_code.lower() == bg_code.lower():
        data = {
            "code": 1,
            "msg": 'ok',
            "data": []
        }
        return JsonResponse(data)
    else:
        data = {
            "code": 2,
            "msg": "验证码错误",
            "data": []
        }
        return JsonResponse(data)

day07/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
    <img src="/app7/img" alt="">
    <br>
    <input type="text" id = "my_code">
    <br>
    <button id="commit">提交</button>
</body>
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}"></script>
<script src="//cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.js"></script>
<script>
    {#提交按钮得点击事件#}
    $("#commit").click(function () {
        {#获取csrf值#}
        var csrftoken = $.cookie("csrftoken")
        console.log(csrftoken)
        {#拿input标签里得值#}
        var code = $("#my_code").val();
        $.ajax({
            url:"/app7/confirm",
            data:{
                "code":code,
                "csrfmiddlewaretoken":csrftoken
            },
            method:"post",
            success:function (res) {
                console.log(res);
                if(res.code == 1){
                    {# 成功时的处理#}
                    alert(res.msg);
                }else{
                    {#失败时的处理#}
                    alert(res.msg);
                }
            },
            error:function () {
                alert("电脑可能没网");
            }
        })
    })
    $("img").click(function () {
        $(this).attr("src","/app7/img" + Math.random());
    })
</script>
</html>

day07/templates/paginator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <ul>
            {% for p in persons %}
                <li>{{ p.name }}的年纪是{{ p.age }}</li>
                {% empty %}
                <h1>没有啦</h1>
            {% endfor %}
        </ul>
        <nav aria-label="Page navigation">
         <ul class="pagination">
            <li>
{#              <a href="{% url 'app7:person' page.previous_page_number %}" aria-label="Previous">#}
{#                <span aria-hidden="true">&laquo;</span>#}
{#              </a>#}
{#                如果有前一页  反向解析得参数正常配置#}
                {% if page.has_previous %}
                    <a href="{% url 'app7:person' page.previous_page_number %}" aria-label="Previous">
                       <span aria-hidden="true">前一页</span>
                    </a>
{#                    没有前一页  反向解析得参数为1#}
                {% else %}
                    <a href="{% url 'app7:person' 1 %}" aria-label="Previous">
                       <span aria-hidden="true">首页</span>
                    </a>
                {% endif %}
            </li>
{#            循环生成  页码按钮#}
             {% for page_num  in page_range %}
                <li><a href="{% url 'app7:person' page_num %}">{{ page_num }}</a></li>
             {% endfor %}
{#             最后一页#}
            <li>
                {% if page.has_next %}
{#                    如果有下一页，请求参数正常使用#}
                    <a href="{% url 'app7:person' page.next_page_number %}" aria-label="Next">
                       <span aria-hidden="true">下一页</span>
                    </a>
                {% else %}
                    <a href="{% url 'app7:person' last_page %}" aria-label="Next">
                       <span aria-hidden="true">尾页</span>
                    </a>
                {% endif %}
            </li>
            </ul>
            </nav>

    </div>
</body>
</html>