AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^axf/",include('app.urls',namespace="axf")),
]

AXF/app/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r"^home$",home,name="home"),
    url(r"^market$",market,name="market"),
    url(r"^market_with_params/(\d+)/(\d+)/(\d+)", market_with_params, name="market_with_params"),
    url(r"^cart$",cart,name="cart"),
    url(r"^mine$",mine,name="mine"),
    url(r"^register$",RegisterAPI.as_view(),name="register"),
    url(r"^login$",LoginAPI.as_view(),name="login"),
    url(r"^confirm/(.*)",confirm_api),
    url(r"^logout$",logout_api,name="logout"),
    url(r"^cartapi$",cart_api,name="cart_api"),
    url(r"^cart_status$",cart_status_api),
    url(r"^select_all_api$",select_all_api),
    url(r"^cartitem_api$",cartitem_api),
    url(r"^order$",order_api,name="order")
]

AXF/templates/cart/cart.html
{% extends 'base/base_main.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/cart/css/cart.css' %}">
{% endblock %}

{% block content %}
    <div id="cart">
        <h3>购物车</h3>
        <div class="full">
            <section>
                <ul>
                    <li>收货人：{{ uname }}
                        <div>
                            <p>修改&gt;&gt;</p>
                        </div>
                    </li>
                    <li>电  话：{{ phone }}</li>
                    <li>收货地址：{{ address }}</li>
                </ul>

{#                闪送超市#}
                <div class="bill">
                    <p>闪送超市</p>
                    <p>满100减30</p>
                    <a href="">凑单专区</a>
                </div>

                <div class="delivery">
                    <span>收货时间</span>
                    <span>一小时可达</span>
                    <a href="">可预订&gt;&gt;</a>
                </div>

                <div class="delivery">
                    <span>备注留言：</span>
                    <input type="text" placeholder="你有帝王之象">
                </div>

                <menu>
                    <ul>
                        {% for i in cart_items %}
                            <li class="menuList" c_id="{{ i.id }}">
                                <div class="confirm">
                                    <span>
                                        {% if i.is_select %}
                                            <span>√</span>
                                            {% else %}
                                            <span></span>
                                        {% endif %}
                                    </span>
                                </div>

                                <a href="#">
                                    <img src="{{ i.goods.productimg }}" alt="">
                                    <p>
                                        {{ i.goods.productname }}
                                    </p>
                                    <p class="presentPrice">{{ i.goods.price }}</p>
                                </a>

                                <section>
                                    <button class="subBtn">-</button>
                                    <span>{{ i.num }}</span>
                                    <button class="addBtn">+</button>
                                </section>

                            </li>
                        {% endfor %}

                    </ul>
                </menu>

                <div class="payTheBill">
                    <div class="all_select">
                        <span>
                            {% if is_select_all %}
                                <span>√</span>
                                {% else %}
                                <span></span>
                            {% endif %}
                        </span>
                    </div>
                    <p>
                        <span>全选</span>
                        <span>共计:</span>
                        <span id="money">{{ sum_money }}</span>
                    </p>
                    <span><a href="{% url 'axf:order' %}">下单</a></span>
                </div>
            </section>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'axf/cart/js/cart.js' %}"></script>
{% endblock %}